apiVersion: v1
kind: Service
metadata:
  name: to0scheduler-service
spec:
  type: NodePort
  selector:
    app: to0scheduler
  ports:
    - name: to0scheduler-port
      port: 8049
      targetPort: 8049
